=== MarekBrandt/swiat-seriali-pl-website-html/etap1/seriale.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xs:element name="strona">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="autor" type="autorType">
				</xs:element>
				<xs:element name="data" type="xs:date">
				</xs:element>
				<xs:element name="seriale" type="serialeType"></xs:element>
				<xs:element name="linkiOgolne">
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="link" maxOccurs="unbounded"></xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="autorType">
		<xs:sequence>
			<xs:element name="imie" type="imieType"/>
			<xs:element name="nazwisko" type="nazwiskoType"/>
		</xs:sequence>
		<xs:attribute name="wiek" type ="wiekType"></xs:attribute>
		<xs:attribute name="plec">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="male"/>
					<xs:enumeration value="female"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="narodowosc">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:pattern value="[a-z][a-z]"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:simpleType name="imieType">
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="nazwiskoType">
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="wiekType">
		<xs:restriction base="xs:decimal">
			<xs:maxInclusive value="120"/>
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="source" type="xs:anyURI"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="serialeType">
		<xs:sequence>
			<xs:element name="serial" type ="serialType" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="serialType">
		<xs:sequence>
			<xs:element name="daneSerialu" type="daneSerialuType"></xs:element>
		</xs:sequence>
		<xs:attribute ref="produkcja"/>
		<xs:attribute ref="sezonow"/>
		<xs:attribute ref="mojaOcena"/>
	</xs:complexType>
	<xs:complexType name="daneSerialuType">
		<xs:sequence>
			<xs:element name="kluczowe" type="kluczoweType"/>
			<xs:element name="poboczne" type="poboczneType"/>	
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="kluczoweType">
		<xs:group ref="kluczoweSerialu"/>
	</xs:complexType>
	<xs:complexType name="poboczneType">
		<xs:sequence>
			<xs:element name="tworca" type="xs:string"/>
			<xs:element name="opis" type="opisType"/>
			<xs:element name="gatunki" type ="gatunkiType"/>
			<xs:element name="zdjecie" type="linkType">
			</xs:element>
			<xs:element name="linki">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="link" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="opisType" mixed="true">
		<xs:sequence>
			<xs:element name="pierwszeZdanie" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="gatunkiType">
		<xs:sequence>
			<xs:element name="gatunek" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="kluczoweSerialu">
		<xs:sequence>
			<xs:element ref="tytul"/>
			<xs:element ref="krotkiOpis"/>
		</xs:sequence>
	</xs:group>
	<xs:element name="tytul" type="tytulType"/>
	<xs:element name="krotkiOpis" type="krotkiOpisType"/>
	<xs:simpleType name="tytulType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="krotkiOpisType">
		<xs:restriction base="xs:string">
			<xs:minLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attribute name="source" type="xs:anyURI"/>
	<xs:attribute name="produkcja" type="xs:string"/>
	<xs:attribute name="sezonow" type="xs:byte"/>
	<xs:attribute name="mojaOcena">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:maxInclusive value="10"/>
				<xs:minInclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	<xs:element name="link" type="linkType"/>
</xs:schema>

=== MarekBrandt/swiat-seriali-pl-website-html/etap1/seriale.xml
<?xml version="1.0" encoding="utf-8"?>
<strona xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="seriale.xsd">
	<autor wiek="19" plec="male" narodowosc="pl">
		<imie>Marek</imie>
		<nazwisko>Brandt</nazwisko>
	</autor>
	<data>
		2020-11-19
	</data>
	<seriale>
		<serial produkcja="USA" sezonow="5" mojaOcena="10">
			<daneSerialu>
				<kluczowe>
					<tytul>Breaking Bad</tytul>
					<krotkiOpis>Gdy nauczyciel chemii dowiaduje się, że ma raka, postanawia rozpocząć produkcję metamfetaminy, by finansowo zabezpieczyć swoją rodzinę.</krotkiOpis>
				</kluczowe>
				<poboczne>
					<tworca>Vince Gilligan</tworca>
					<opis>
						<pierwszeZdanie>Jeden z najbardziej znanych i cenionych seriali na świecie.</pierwszeZdanie>
						Opowiada historię Waltera White'a, który zmienia się nie do poznania gdy otrzymuję diagnozę od lekarza.
						Serial może być materiałem do rozmowy na wiele ciekawych tematów. Jeśli jesteś fanem seriali, koniecznie musisz znać ten.
						Warto zaznaczyć, że powstał prequel o tytule "Better call Saul", który również wnosi bardzo wiele do świata z "Breaking Bad".
					</opis>
					<gatunki>
						<gatunek>Dramat</gatunek>
						<gatunek>Kryminał</gatunek>
					</gatunki>
					<zdjecie source="img/bb.jpg">
						Breaking Bad
					</zdjecie>
					<linki>
						<link source="https://www.filmweb.pl/serial/Breaking+Bad-2008-430668">Filmweb</link>
						<link source="https://www.imdb.com/title/tt0903747/?ref_=nv_sr_srsg_1">IMBd</link>
					</linki>
				</poboczne>
			</daneSerialu>
		</serial>
		<serial produkcja="USA" sezonow="5" mojaOcena="9">
			<daneSerialu>
				<kluczowe>
					<tytul>Better call Saul</tytul>
					<krotkiOpis>Pechowy prawnik robi wszystko, by zaistnieć na sądowej scenie w Albuquerque.</krotkiOpis>
				</kluczowe>
				<poboczne>
					<tworca>Vince Gilligan, Peter Gould</tworca>
					<opis>
						<pierwszeZdanie>Serial "Better call Saul" jest prequelem serialu "Breaking Bad".</pierwszeZdanie> Jeśli jesteś fanem tego drugiego, to z czystym sercem mogę polecić ci ten serial. Mimo tego, jeżeli serialu "Breaking Bad" nie znasz, nic nie stoi na przeszkodzie, by swoją przygodę rozpocząć właśnie od Saula. Serial rozgrywa się w okolicach Albuquerque. Niesamowite kadry przykuwają oko i pozostają w pamięci na długo. Opowiada o ciężkiej drodze, którą Saul Goodman musi przejść, by zostać prawnikiem. Połączenie komedii i dramatu, znakomicie się w tym przypadku udało.
					</opis>
					<gatunki>
						<gatunek>Dramat</gatunek>
						<gatunek>Komedia</gatunek>
						<gatunek>Kryminał</gatunek>
					</gatunki>
					<zdjecie source="img/bcs.jpg">
						Better call Saul
					</zdjecie>
					<linki>
						<link source="https://www.filmweb.pl/serial/Zadzwo%C5%84+do+Saula-2015-697645">Filmweb</link>
						<link source="https://www.imdb.com/title/tt3032476/?ref_=nv_sr_srsg_0">IMBd</link>
					</linki>
				</poboczne>
			</daneSerialu>
		</serial>
		<serial produkcja="USA" sezonow="5" mojaOcena="10">
			<daneSerialu>
				<kluczowe>
					<tytul>Lucyfer</tytul>
					<krotkiOpis>Nieszczęśliwy i znudzony swoim bytem Lucyfer Morningstar porzuca funkcję Władcy Piekieł, po czym udaje się do Los Angeles, gdzie zostaje właścicielem luksusowego klubu nocnego.</krotkiOpis>
				</kluczowe>
				<poboczne>
					<tworca>Tom Kapinos</tworca>
					<opis>
						<pierwszeZdanie>UWAGA! Serial niezwykle wciąga.</pierwszeZdanie> Oglądanie serialu "Lucyfer", daje niesamowicie dużo frajdy.
						Może rzecz w tym, że głównym bohaterem jest charyzmatyczny, satyryczny i prawdomówny diabeł.
						Nawet jeśli jesteś wierzący, to będziesz się dobrze bawił, bo serial nie próbuje wyśmiewać chrześcijaństa.
						Zdecydowanie polecam. Chodź radzę zastanowić się, czy masz w danym momecie sporo czasu, bo prawdopodobnie na 1 odcinku się nie skończy.
					</opis>
					<gatunki>
						<gatunek>Fantasy</gatunek>
						<gatunek>Kryminał</gatunek>
					</gatunki>
					<zdjecie source="img/lucyfer.webp">
						Lucyfer
					</zdjecie>
					<linki>
						<link source="https://www.filmweb.pl/serial/Lucyfer-2016-742520">Filmweb</link>
						<link source="https://www.imdb.com/title/tt4052886/?ref_=nv_sr_srsg_0">IMBd</link>
					</linki>
				</poboczne>
			</daneSerialu>
		</serial>
		<serial produkcja="Wielka Brytania" sezonow="4" mojaOcena="8">
			<daneSerialu>
				<kluczowe>
					<tytul>Sherlock</tytul>
					<krotkiOpis>John Watson jest lekarzem wojskowym, który niedawno wrócił z wojny. Gdy poznaje genialnego detektywa Sherlocka Holmesa, zaczyna pomagać mu w rozwiązywaniu zagadek kryminalnych.</krotkiOpis>
				</kluczowe>
				<poboczne>
					<tworca>Steven Moffat, Mark Gatiss</tworca>
					<opis>
						<pierwszeZdanie>Serial który muszą obejrzeć fani powieści detektywistycznych.</pierwszeZdanie> Do ekranu przykuwa zawiłość zagadek, jak i sposób prezentacji
						rozwiązań. Nie do opisania jest radość z samodzielnego wpadnięcia na trop, szybciej niż główny bohater.
						Mroczny Londyn tylko dodaje kolorytu.
					</opis>
					<gatunki>
						<gatunek>Dramat</gatunek>
						<gatunek>Kryminał</gatunek>
					</gatunki>
					<zdjecie source="img/sherlock.jpg">
						Sherlock
					</zdjecie>
					<linki>
						<link source="https://www.filmweb.pl/serial/Sherlock-2010-528992">Filmweb</link>
						<link source="https://www.imdb.com/title/tt1475582/?ref_=nv_sr_srsg_0">IMBd</link>
					</linki>
				</poboczne>
			</daneSerialu>
		</serial>
		<serial produkcja="USA" sezonow="3" mojaOcena="10">
			<daneSerialu>
				<kluczowe>
					<tytul>Stranger Things</tytul>
					<krotkiOpis>
						Podczas powrotu do domu znika dwunastoletni Will Byers. Zaginięcie chłopca jest początkiem dziwnych i niebezpiecznych wydarzeń trapiących prowincjonalne miasteczko.
					</krotkiOpis>
				</kluczowe>
				<poboczne>
					<tworca>Matt Duffer, Ross Duffer</tworca>
					<opis>
						<pierwszeZdanie>Serial "Stranger Things" pomaga odnaleźć w sobie dziecko na nowo.</pierwszeZdanie> Obserwowanie perypetii grupy nastolatków sprawia czystą przyjemność.
						Ale uważajcie, pewne momenty w tym serialu są w stanie zmrozić krew w żyłach, nawet u najbardziej zagorzałych fanów horrorów.
					</opis>
					<gatunki>
						<gatunek>Dramat</gatunek>
						<gatunek>Horror</gatunek>
						<gatunek>Sci-Fi</gatunek>
					</gatunki>
					<zdjecie source="img/st.jpg">
						Stranger Things
					</zdjecie>
					<linki>
						<link source="https://www.filmweb.pl/serial/Stranger+Things-2016-750359">Filmweb</link>
						<link source="https://www.imdb.com/title/tt4574334/?ref_=nv_sr_srsg_0">IMBd</link>
					</linki>
				</poboczne>
			</daneSerialu>
		</serial>
		<serial produkcja="Irlandia/Kanada" sezonow="6" mojaOcena="9">
			<daneSerialu>
				<kluczowe>
					<tytul>Wikingowie</tytul>
					<krotkiOpis>Młody wiking, Ragnar Lothbrok, pragnie, by wyprawy łupieżcze odbywały się nie tylko na wschód, ale także w kierunku przeciwnym.</krotkiOpis>
				</kluczowe>
				<poboczne>
					<tworca>Michael Hirst</tworca>
					<opis>
						<pierwszeZdanie>Pomimo tego, że serial jest przedstawicielem gatunku dramatów historycznych, to nie obawiajcie się że będzie to nudna lekcja historii.</pierwszeZdanie>
						Historia Ragnara jest pasjonująca. Twórca zadbał o to, by widz zagłębił się w fabułe i razem z bohaterami przeżywał radości, smutki,
						podboje i zdrady. Zdecydowanie warte obejrzenie.
					</opis>
					<gatunki>
						<gatunek>Dramat historyczny</gatunek>
					</gatunki>
					<zdjecie source="img/wiking.jpg">
						Wikingowie
					</zdjecie>
					<linki>
						<link source="https://www.filmweb.pl/serial/Wikingowie-2013-659055">Filmweb</link>
						<link source="https://www.imdb.com/title/tt2306299/?ref_=nv_sr_srsg_0">IMBd</link>
					</linki>
				</poboczne>
			</daneSerialu>
		</serial>
	</seriale>
	<linkiOgolne>
		<link source="https://www.filmweb.pl">Filmweb</link>
		<link source="https://www.imdb.com">IMBd</link>
	</linkiOgolne>
</strona>
